title: tandavala website
author: tandavala
email: jose.tandavala@gmail.com
theme: humberto
humberto:
  name: Jose tandavala
  tagline: Developer. Sofware
  date_format: "%b %-d, %Y"
  sitemap: true

  # generate social links in footer
  social_links:
    github: tandavala
    rss: rss
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
theme: humberto
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
