title: José Tandavala 
author: tandavala
email: jose.tandavala@gmail.com
github: https://github.com/tandavala
linkedIn: https://www.linkedin.com/in/jos%C3%A9-tandavala-76085a98/\
twitter: https://twitter.com/_tandavala
about: Software Developer.

social_links:
  twitter: tandavala
  github: tandavala
  linkedIn: tandavala
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
